#!/bin/python

import sys
N = int(raw_input().strip())
for i in xrange(1,11):
    print(str(N) + " x " + str(i) + " = " + str(N*i))
#Very simple and elegant code PYTHON 2.0 VERSION.
#IF YOU WANT TO USE PYTHON THREE, SIMPLY CHANGE raw_input to input and change xrange to range and it should work.
